### ISSUE TITLE
Game doesn't fully close upon Quitting

### ISSUE THREAD

**Issue by pulentiu** [gennariarmando/v-hud#105]
**Describe the bug**
When you quit the game, the game doesn't fully close which leads to several problems, such as:
- You can't restart the game unless you open Task Manager and end the 'gta_sa.exe' task;
- If your window mode is set to Fullscreen, the "Exit to Windows" screen will be stuck on your screen no matter what you do, until you find a way to, again, end the task using Task Manager (or any task-ending application for that matter)

**To Reproduce**
Simply enter the game and then press the Quit button at the Landing Page or under the 'Game' tab in the in-game Pause Menu.

**Expected behavior**
The game fully closes with no problem whatsoever.

**Screenshots**
![image](https://user-images.githubusercontent.com/110244963/181786745-75731ce7-7e4e-49e6-a75e-affccec62d0b.png)

**Additional context**
I do have the following mods installed:
- [Essentials Pack](https://www.mixmods.com.br/2019/06/sa-essentials-pack/) (I deleted the Windowed Mode mod)
- [PortableGTA](https://www.mixmods.com.br/2021/06/iii-vc-sa-portablegta-change-saves-folder-mudar-pasta-user-files/)
- [GInput](https://www.mixmods.com.br/2021/01/iii-vc-sa-ginput-melhor-suporte-para-controles/)

However, I don't think the mods affected this in any way.

**Comment by gennariarmando** [comment]
Remove all the mods and try on vanilla, that's all I can say.

**Comment by pulentiu** [comment]
I did some testing, and found out it was because GInput was installed through modloader instead of being in the game directory.
Sorry for wasting your time
