### ISSUE TITLE
BGM main-menu keeps playing

### ISSUE THREAD

**Issue by Jedrzej94** [gennariarmando/v-hud#12]
**Describe the bug**
My GTA SA boots up real quick (like the progress bar fills up within miliseconds) and I think V-HUD is still loading some stuff in the background and if I select "Story Mode" too soon, I will have the main menu music playing all the time while playing the game.

**To Reproduce**
1. Start the game (you need to have a really fast PC or something, I dunno why my GTA SA boots up so fast)
2. Select Story Mode

**Expected behavior**
Stop playing the main-menu bgm.

edit://
I suppose it's related to: "Initialised SoundManager" in the CMD prompt.

P.S
Can't you run the cmd with `-s` param for it to not appear?

**Comment by gennariarmando** [comment]
This should already have been fixed in the latest updates, are you testing the first pre-release?

**Comment by Jedrzej94** [comment]
> This should already have been fixed in the latest updates, are you testing the first pre-release?

I just downloaded this:
https://github.com/gennariarmando/v-hud/releases/tag/v0.930

**Comment by Jedrzej94** [comment]
BTW I can't reconfigure key-bindings via game UI and I can't pass Cesar Vialpando mission Low-Rider dance.

**Comment by Jedrzej94** [comment]
I have edited manually my `controls.xml` and set up these as:
```	<VEHICLE_TURRETLEFT value="3" />
	<VEHICLE_TURRETRIGHT value="4" />
	<VEHICLE_TURRETUP value="1" />
	<VEHICLE_TURRETDOWN value="2" />```

**Comment by gennariarmando** [comment]
Ok, so this issue can be closed.

**Comment by Jedrzej94** [comment]
Not really, how's that closed? lol You don't bother about 3 issues I have mentioned already?

**Comment by gennariarmando** [comment]
This issues have been fixed already, you're using an outdated version.

**Comment by Jedrzej94** [comment]
Hey, if you could re-open this issue.

Here's how I manage to reproduce the Audio BGM issue:
https://www.youtube.com/watch?v=5IISkKWD2S8

That's what happens when I act "inpatient". But if I give it like a 2-3 seconds before hitting "Story Mode" then audio is initialised successfully.

**Comment by Jedrzej94** [comment]
@gennariarmando
