### ISSUE TITLE
Using weapon wheel during cutscenes or other activities

### ISSUE THREAD

**Issue by Jedrzej94** [gennariarmando/v-hud#18]
Weapon wheel appears (when using mouse wheel) during some cutscenes, for example during Doberman mission where the game explains to you what are the Gang territories etc.

or while using gym stuff
![gta_sa_OAAqLnKmVI](https://user-images.githubusercontent.com/15942408/147383269-562a521c-bec6-47e8-abf6-1f4a09749a1e.jpg)

**Comment by Jedrzej94** [comment]
Yeah, mouse-wheel tends to do some weird shit:)
![image](https://user-images.githubusercontent.com/15942408/147383424-7dd33779-7515-47a0-94ca-79d168387533.png)

**Comment by gennariarmando** [comment]
Hilarious, thanks for reporting all this issues.

**Comment by Jedrzej94** [comment]
![image](https://user-images.githubusercontent.com/15942408/147383814-3eee58f9-d5bf-4f1d-8e5f-7ddf329b8174.png)
Just one more:) You get the point
