### ISSUE TITLE
Radio icon does not dissappear after entering a vehicle

### ISSUE THREAD

**Issue by Jedrzej94** [gennariarmando/v-hud#19]
You are forced to change radio station for it to start the delay to hide the icon (I know it's still WIP - I mean the radio wheel overall)
Reporting anyway.

![image](https://user-images.githubusercontent.com/15942408/147383898-f1dffcc0-a1db-45a7-b46b-da77a144eb33.png)

**Comment by gennariarmando** [comment]
I can't replicate this, how often does it happens?

**Comment by Jedrzej94** [comment]
Start the game > Go in vehicle _(icon doesn't appear the first time you enter)_ > Select any radio station > Icon disappears > ESC > Load game (any save) > Enter vehicle > Icon appears and never goes away
