### ISSUE TITLE
Main menu slightly too large on 5:4 aspect ratio

### ISSUE THREAD

**Issue by Zolika1351** [gennariarmando/v-hud#2]
The main menu/landing page seems to look a bit larger than it does in V at 5:4 resolutions (1280x1024 in this shot)
Notice how the box in the middle reaches the edge of the screen

![](https://cdn.discordapp.com/attachments/709753582303576134/915620536862773268/unknown.png)

**Comment by gennariarmando** [comment]
Thanks for reporting this issue.
I just pushed some code that should resolve this, can you please check if it's now fixed?

**Comment by Zolika1351** [comment]
Looks fine now, thanks
![image](https://user-images.githubusercontent.com/10864159/144623401-e159a6f7-63b9-428e-97f4-9a59e1d2a7d2.png)
