### ISSUE TITLE
Map icons issue (Mission with Catalina - Unknown icon)

### ISSUE THREAD

**Issue by Jedrzej94** [gennariarmando/v-hud#20]
So I just got Cesar call in Angel Pine to visit his cousin. CJ doesn't know her yet, she appears as '?' question mark (unknown) map icon. It is visible in the mini-map HUD:
![image](https://user-images.githubusercontent.com/15942408/147383998-b3d5e553-2e43-46d5-a409-877572fab609.png)

but I can't find that map-icon for shit on the big map. Even though she appears in the Legend.
![image](https://user-images.githubusercontent.com/15942408/147384024-6b8904db-83e3-40fd-88ae-85f5681719e7.png)

**Comment by Jedrzej94** [comment]
I'm blind af.
![image](https://user-images.githubusercontent.com/15942408/147387264-a63434fe-2923-48c4-b2d7-6e94e30f6853.png)

Icons were overlapping.

Is there any way to increase the z-index of the sprite/change creation order or something?

**Comment by gennariarmando** [comment]
Sadly not. You usually zoom in to make them expand and be more visible.
