### ISSUE TITLE
Game doesn't freeze in the pause menu && no slow-down in weapon wheel

### ISSUE THREAD

**Issue by Jedrzej94** [gennariarmando/v-hud#21]
When you press ESC game doesn't stop (it does in 0.930)
When you hold TAB to open weapon wheel menu it doesn't slow down your game (it does in 0.930)

works in beta (just tested). Doesn't work on 0.935

**Comment by Jedrzej94** [comment]
Also when you go to the pause menu and go back in-game it doesn't restore the radio. I have to re-enter my vehicle for radio to start playing again.

**Comment by gennariarmando** [comment]
This is supposed to happen only with SAMP, does it happens offline as well?

**Comment by Jedrzej94** [comment]
I have uninstalled SA-MP from my GTA SA and it started working again. I think it doesn't detect if you are actually playing SAMP

**Comment by Jedrzej94** [comment]
Even though, if that's supposed to be for SA-MP, I shouldn't be able to have control over my character while in pause-menu. Whenever I clicked I was shooting etc.

**Comment by gennariarmando** [comment]
That's weird, I tested both offline and with SAMP multiple times.

**Comment by Jedrzej94** [comment]
I have seen you posted many fixes. Let me know when you release it, I'll download it and test it @gennariarmando

**Comment by gennariarmando** [comment]
It will take a bit of time for a new release, if you can, please clone the repo and build from source.

**Comment by Jedrzej94** [comment]
@gennariarmando do you have any Discord or anywhere else where I can message you?

**Comment by Jedrzej94** [comment]
I'm asking because I'm having some error when building the project. I suppose that's plugin-sdk related stuff, but since I'm unsure I wanted to talk to you via Discord @gennariarmando

**Comment by gennariarmando** [comment]
Yeah #6978

**Comment by Jedrzej94** [comment]
> Yeah #6978

This? MrHakai86#6978 If so, just sent a friend request

**Comment by gennariarmando** [comment]
No, it's:  _AG#6978
