### ISSUE TITLE
GPS navigation cuts

### ISSUE THREAD

**Issue by Jedrzej94** [gennariarmando/v-hud#22]
I'm not sure what do you use (vehicle position road nodes?) or if it's GTA SA limitation but GPS cuts the path to follow. I'm unsure if it happened in LS, I didn't notice, maybe Angle Pine is poorly done?

![image](https://user-images.githubusercontent.com/15942408/147385323-0ea29b7a-3e66-4dce-ab60-450a25feb6e1.png)

**Comment by gennariarmando** [comment]
This is a game limit sadly I wasn't able to increase it yet.
