### ISSUE TITLE
Font Bug

### ISSUE THREAD

**Issue by FallenAnother** [gennariarmando/v-hud#27]
I downloaded the mod today, and I used to play with the old 2Pac hud without problems. But, since I installed the version of the mod, the fonts of the game stay purely blank. I don't know how to solve this, since I already tried for hours.
![SnapCrab_GTA San Andreas_2021-12-25_19-59-40_No-00](https://user-images.githubusercontent.com/96667497/147394244-077ecc9f-4adf-4e52-9cae-a9df78f5faba.png)

**Comment by gennariarmando** [comment]
There is currently no bug related to font that acts this way.

There are incompatibilities with mods that improve graphics, if you have any remove it.
The best way I think it's to test on vanilla.
Just in case you're missing some files, download latest archive and re try.

**Comment by FallenAnother** [comment]
I got rid of everything, but the result it's still the same.

**Comment by FallenAnother** [comment]
Cleaned the entire mods folder, still bugging.

**Comment by FallenAnother** [comment]
Oh wait, I just solved. Looks like my pc can't run the mod without using an virtual graphic card. After all, it was just my shitty pc-
