### ISSUE TITLE
Game crash when starting a game

### ISSUE THREAD

**Issue by Lucas559-noob** [gennariarmando/v-hud#31]
**Describe the bug**
When starting a game, it crash.

**To Reproduce**
1. Go to start menu
2. Click on play or idk the button
3. See crash

**Expected behavior**
Load a save file or start a new game.

**Additional context**
SRC 
[scrlog.log](https://github.com/gennariarmando/v-hud/files/7777301/scrlog.log)
modloader log 
[modloader.log](https://github.com/gennariarmando/v-hud/files/7777303/modloader.log)

**Comment by gennariarmando** [comment]
More informations are needed, like all the other mods you use.

**Comment by n1tr0xz** [comment]
removes GInput from modloader

**Comment by Lucas559-noob** [comment]
> More informations are needed, like all the other mods you use.

well even without modloder and cleo it crash, so probably is some of those mods that you place on game directory

**Comment by Lucas559-noob** [comment]
After game reinstalled, lets see again
[scrlog.log](https://github.com/gennariarmando/v-hud/files/7778142/scrlog.log)
[modloader.log](https://github.com/gennariarmando/v-hud/files/7778143/modloader.log)
![image](https://user-images.githubusercontent.com/54007604/147430268-f6591b7e-9e8c-41a8-8420-86494556ba7d.png)
only in modloader
essentials have those 
![image](https://user-images.githubusercontent.com/54007604/147430290-25449ed8-cc55-486c-a3f9-6fbddcde2f61.png)
cleo only those things 
![image](https://user-images.githubusercontent.com/54007604/147430314-605e3c1d-5c17-45aa-bfde-bb30ac0a7749.png)
I will delete save games, if thats the problem since its the same error

**Comment by Lucas559-noob** [comment]
yeah the problem was a saved game or some saved stuff
