### ISSUE TITLE
Constructive criticism

### ISSUE THREAD

**Issue by n1tr0xz** [gennariarmando/v-hud#32]
A criticism I think constructive, the mod is still heavy, takes a lot of fps, if you can optimize it / improve I appreciate it.

**Comment by Jedrzej94** [comment]
What are your PC specs huh? I literally have no issues at all.

**Comment by Lucas559-noob** [comment]
yeah it take some fps, like if the UI wanted to show all time, then it like loop, or is because it add many features like the weapon wheel, and idk what more
my pc is not the best
windows 8.1, 4gb ram, HD Graphics 4000(yeah its old, 2014), I3 2.4ghz(quad core, but game only use 1)
