### ISSUE TITLE
Weird 3D Radar Distortion

### ISSUE THREAD

**Issue by mistermayomayo** [gennariarmando/v-hud#37]
**Describe the bug**
Weird Distortion on 3D Vehicle Radar when FPS drop to 20 or lower
The bug will gone when running on 30 FPS and higher but sometimes wlll present even on this framerate

**To Reproduce**
Run the game and set the fps to 20 or lower, ride any cars or bikes. 
![image](https://user-images.githubusercontent.com/96839507/147730582-4f482a20-d361-432f-bb3a-ba6baecf6178.png)

**Comment by R3SiZT3D** [comment]
Upload a screenshot of ur game directory please, i can help u

**Comment by mistermayomayo** [comment]
@R3SiZT3D 
![image](https://user-images.githubusercontent.com/96839507/147873182-ab802834-7754-4603-b4fd-05c2bfe72e88.png)
