### ISSUE TITLE
directx9?

### ISSUE THREAD

**Issue by gusdepalma** [gennariarmando/v-hud#40]
So, is not compatible with directx12? because 0.940 version still crashing in my game.

**Comment by gennariarmando** [comment]
Directx9 and above, if you have other mods installed please retry on a clean game.

**Comment by ukenjutsu** [comment]
> Directx9 and above, if you have other mods installed please retry on a clean game.

I have the same problem. Still crashing even on a clean game (only sa-mp installed), tested in singleplayer and multiplayer

**Comment by lazytspo** [comment]
unfortunately it crashes for Me TOO!!! i have DirectX12
