### ISSUE TITLE
At speed up the car, get the issue (see screenshot)

### ISSUE THREAD

**Issue by niresh1234** [gennariarmando/v-hud#45]
Hi, when i speedup my car i get the issue (see screenshot)

**One More issue:**
**Some time ESC Key Not Work**

**I use this mods or fixes**
- This Hud (v 0.940)
- Ultimate Asi Loader (Letest)
- Modloader (Letest)
- WidescreenFix (Letest)
- SkyGFX (4.2b)
- Silent Patch (Letest)

**I Hope You will fix it**

**Screenshot Here**
![Screenshot-(155)](https://user-images.githubusercontent.com/98110551/150377676-13d3f8f6-d5f2-46b0-90ad-6335826dd2b3.jpg)
Thank You! and Good Luck!

**Comment by gennariarmando** [comment]
Are you sure this is related to this mod?

**Comment by niresh1234** [comment]
Yes, because I try without this Hud and Not Get Such Issue.. I Also Use DK22pac's 5-HUD But Not Get This Problem (Trying this tasks without removing other mods, get problem only with this HUD)

**Comment by gennariarmando** [comment]
Can't replicate in any way at this moment

**Comment by niresh1234** [comment]
Hi, Few More Things, That I Noticed

- When I Play In Windowed Mod Not Get Such Issue
- Only Get This Issue in Full Screen Mod
- When I Load The Game In Full Screen Mod I Get This Issue, The Press Alt+Enter To Windowed Mod, and Suddenly Not Get The Issue in Windowed Mod

**I Mean, I Think Problem in Full Screen Mod**

Sorry for my bad English.

**Comment by niresh1234** [comment]
Hi, Few More Things, That I Noticed

- When I Play In Windowed Mod Not Get Such Issue
- Only Get This Issue in Full Screen Mod
- When I Load The Game In Full Screen Mod I Get This Issue, Then Press Alt+Enter To Windowed Mod, and Suddenly Not Get The Issue in Windowed Mod

I Mean, I Think Problem in Full Screen Mod

Sorry for my bad English.

**Comment by niresh1234** [comment]
Hi, Few More Things, That I Noticed

(If I Played Car at High Speed)
- When I Play In Windowed Mod Not Get Such Issue
- Only Get This Issue in Full Screen Mod
- When I Load The Game In Full Screen Mod I Get This Issue, Then Press Alt+Enter To Windowed Mod, and Suddenly Not Get The Issue in Windowed Mod

I Mean, I Think Problem in Full Screen Mod

Sorry for my bad English.

**Comment by niresh1234** [comment]
Hi, Few More Things, That I Noticed

(If I Played Car at High Speed)
- When I Play In Windowed Mod Not Get Such Issue
- Only Get This Issue in Full Screen Mod
- When I Load The Game In Full Screen Mod I Get This Issue, Then Press Alt+Enter To Windowed Mod, and Suddenly Not Get The Issue in Windowed Mod

I Mean, I Think Problem in Full Screen Mod

Sorry for my bad English.

**Comment by niresh1234** [comment]
Hi, Few More Things, That I Noticed

(If I Played Car at High Speed)
- When I Play In Windowed Mod Not Get Such Issue
- Only Get This Issue in Full Screen Mod
- When I Load The Game In Full Screen Mod I Get This Issue, Then Press Alt+Enter To Windowed Mod, and Suddenly Not Get The Issue in Windowed Mod

I Mean, I Think Problem in Full Screen Mod

Sorry for my bad English.

**Comment by Crowdigger** [comment]
it also stops happening if in the game you change the resolution to fullscreen through the menu.

**Comment by niresh1234** [comment]
Yeas @Crowdigger it works, but why?
@Crowdigger you are also spot this issue?

Hi, @gennariarmando , now every time i start the GTA_SA get this issue, but when I change the resolution in Menu (1st windowed then back Fullscreen) and not getting this issue..

please replay me..

**Comment by Crowdigger** [comment]
Yes, it happens to me too. I do not know the reason.

**Comment by niresh1234** [comment]
Hey @gennariarmando me and aslo @Crowdigger already spot this issue...... please take the action on this issue

**Comment by gennariarmando** [comment]
I still can’t replicate this, won’t take no actions.

**Comment by niresh1234** [comment]
This Display Setting that I Used, You Must Try With This Setting (At least 2-3 time, start the game with GTA_SA Excutable)

![Screenshot (163)](https://user-images.githubusercontent.com/98110551/150908806-9357608d-7efa-4106-bfb3-efb709e8a8c7.png)
![Screenshot (162)](https://user-images.githubusercontent.com/98110551/150908871-e54814a2-510b-4cd4-b2a6-337c1f497069.png)

**Comment by niresh1234** [comment]
This Display Setting that I Used, You Must Try With This Setting (At least 2-3 time, start the game with GTA_SA Excutable)

[ufiles.zip](https://github.com/gennariarmando/v-hud/files/7930537/ufiles.zip)

![Screenshot (163)](https://user-images.githubusercontent.com/98110551/150909171-b5904bce-d8ba-4fa0-a84f-0cb691ba6b59.png)
![Screenshot (162)](https://user-images.githubusercontent.com/98110551/150909216-ed746923-6ec2-414a-a8ae-330b66a1d172.png)

**Comment by niresh1234** [comment]
> I still can’t replicate this, won’t take no actions.

Hi @gennariarmando  .. This Display Setting that I Used, You Must Try With This Setting (At least 2-3 time, start the game with GTA_SA Excutable)

[ufiles.zip](https://github.com/gennariarmando/v-hud/files/7947300/ufiles.zip)
![Screenshot (163)](https://user-images.githubusercontent.com/98110551/151286372-b98314e5-c054-49b0-9652-28168e41a43c.png)
![Screenshot (162)](https://user-images.githubusercontent.com/98110551/151286601-7d05f9ff-ae05-404a-9d5b-a806d0950808.png)

**Comment by niresh1234** [comment]
What can I help you?

**Comment by niresh1234** [comment]
@gennariarmando what can I help you?
