### ISSUE TITLE
ESC Key Problem in Version 0.940

### ISSUE THREAD

**Issue by niresh1234** [gennariarmando/v-hud#46]
ESC Key Issue in v0.940 (Not Get in v0.935)
Sometime ESC Key Not Working

To Reproduce This (You Must Have Any Save File)

- Start Game (GTA San Andreas Executable) (I use Hoodlum)
- Start Game with Story Mod (1st save loaded)
- Play Atlist 1 Minute
- Press ESC (You Go To Main Menu)
- Start New Game (Without loading save file, just new game)

and Try To Press ESC Key
The ESC Key Not Working and Not Going to Main Menu

**Comment by gennariarmando** [comment]
Already fixed in recent commit.

**Comment by niresh1234** [comment]
Mean the issue fixed after v0.940 release?

**Comment by gennariarmando** [comment]
Yeah

**Comment by niresh1234** [comment]
Oh, OK
Have a great day!
