### ISSUE TITLE
Map Options

### ISSUE THREAD

**Issue by niresh1234** [gennariarmando/v-hud#47]
Hi, There are any way to use map options using this HUD?

I mean
At. Normal GTA San Andreas
At Pause Menu > Map > Press Space Key

You can control (Show/Hide) Gang Era, Radar Icons

**Comment by gennariarmando** [comment]
Not possible at the moment. Is this even in GTA V?

**Comment by niresh1234** [comment]
I don't know. Because my pc is not capable to run GTA5. So I Not Play GTA5 in single Time

But see the screenshot (Hide Menu) Option available in GTA5, I don't know what's the use of this option

Image Scource: Google
![IMG_20220121_175929](https://user-images.githubusercontent.com/98110551/150527527-6157028d-fa26-4b1d-aac0-b78961ffea65.png)

**Comment by gennariarmando** [comment]
Has nothing to do with it, it just show and hide the menu itself, leaving you the background visible.

**Comment by niresh1234** [comment]
Oh, But The Option Available in GTA:SA. If You Have Time, Must Add This Option..

Thankyou
