### ISSUE TITLE
Microsoft Visual C++ runtime library error

### ISSUE THREAD

**Issue by EvgeneBooth** [gennariarmando/v-hud#49]
The game does not start. Installed the crashreport mod. And it starts showing an error.
![изображение](https://user-images.githubusercontent.com/98256114/150674453-ae5be105-05c0-4a1d-84d6-649453e02822.png)
All microsoft visual c++ download 
![изображение](https://user-images.githubusercontent.com/98256114/150674549-d7266d69-e2dc-48d5-b16b-1bb9506d7753.png)
Ultimate Asi loader too download.
HUD was inserted into the clean, and into the assembly. In both cases, the game crashed with the same error

**Comment by gennariarmando** [comment]
More informations are needed, please share a crash log if you have one, also the game version and hud version.
Do you have other mods installed?

**Comment by EvgeneBooth** [comment]
HUD version 0.940, gta_sa 1.0 US. Logs are missing.

**Comment by EvgeneBooth** [comment]
A whole day has passed. I have looked at many articles on the Internet related to this error. I tried everything - the result is the same. I don't even have a clue what it might be about. I have already reinstalled the game and put only hud and ultimate asi loader on it. In the old version (0.935) there was no such thing.

**Comment by R3SiZT3D** [comment]
Try with .NET Framework 4.0+

**Comment by EvgeneBooth** [comment]
The .NET Framework was installed before that

**Comment by R3SiZT3D** [comment]
Try using all 


![Screenshot_1](https://user-images.githubusercontent.com/95668930/151042115-12f22816-deef-4011-80fd-dddb8d326ae3.png)

![Screenshot_2](https://user-images.githubusercontent.com/95668930/151042160-a263fd6d-4146-4a2f-943a-cd47ffefb964.png)

**Comment by EvgeneBooth** [comment]
o far, the game crashes. Without a mod that shows error messages, the game just starts running and immediately crashes after a few seconds of sound. Reinstalled everything possible, even downloaded another game.

**Comment by EvgeneBooth** [comment]
Could there be a reason for the error that I have Windows 10 in Russian?

**Comment by EvgeneBooth** [comment]
The bug has been fixed in the new version (0.942). The question is closed
