### ISSUE TITLE
Please Add This Map Options in THIS HUD

### ISSUE THREAD

**Issue by niresh1234** [gennariarmando/v-hud#54]
Hi @gennariarmando , Please Add This Map Options in THIS HUD

**Note: All Screenshots from using 5HUD by DK22Pac**

![1](https://user-images.githubusercontent.com/98110551/151997741-4433c78d-f07d-45ad-9d5e-3eda2af7c490.jpg)

![2](https://user-images.githubusercontent.com/98110551/151997767-2983e426-14ad-4ee7-b816-ea2846861606.jpg)

![3](https://user-images.githubusercontent.com/98110551/151997797-a872f053-d16d-4c88-a98e-a680adf3516b.jpg)

![4](https://user-images.githubusercontent.com/98110551/151997817-aa0f4a41-84bf-4b0e-af22-80da81ca80ca.jpg)

![5](https://user-images.githubusercontent.com/98110551/151997846-364803ee-0601-45b5-a213-cd921b37673e.jpg)

![6](https://user-images.githubusercontent.com/98110551/151997874-aab3128c-2f88-4982-9908-6259426ec0ca.jpg)

![difference](https://user-images.githubusercontent.com/98110551/151997908-b2fdc968-b1df-4137-851d-28d01c079455.jpg)

THANKYOU

**Comment by niresh1234** [comment]
Hi @gennariarmando , Please SEE THIS
![opt-01](https://user-images.githubusercontent.com/98110551/152288833-67a53f76-d364-4706-93f5-36c00fa93d95.jpg)

**Comment by gennariarmando** [comment]
I won't add this.

**Comment by niresh1234** [comment]
No problem
