### ISSUE TITLE
UTF-8 font issue

### ISSUE THREAD

**Issue by Pledix** [gennariarmando/v-hud#58]
**Describe the bug**
Turkish letters render is broken (letters: 'ı','ö','ğ','ş','ç','ü')

![image](https://user-images.githubusercontent.com/22866860/152164414-e9008072-2dbd-4787-a021-c51848bf8b07.png)

**Comment by gennariarmando** [comment]
UTF-8 is currently not supported for other languages than english, try using ANSI encoding.
