### ISSUE TITLE
Bug: Weapon Wheel don't work after mission(s)

### ISSUE THREAD

**Issue by lazytspo** [gennariarmando/v-hud#59]
**Mods Installed:**
VHud **(This mod)**
Ultimate ASI Loader

**What causes this?:**
Any time the mission complete, The TAB key that leads to the weapon wheel is not appearing.
Same thing affects scrolling in Weapon Wheel.

**Affected HUD Parts:**
Weapon Wheel

**Comment by gennariarmando** [comment]
Hud version?

**Comment by lazytspo** [comment]
> Hud version?

0.942

**Comment by lazytspo** [comment]
you need to fix this problem ASAP
