### ISSUE TITLE
Don't start

### ISSUE THREAD

**Issue by R3SiZT3D** [gennariarmando/v-hud#6]
On a clean game with .ASI Loader (dinput8.dll) the game doesn't start. The same behaviour with CLEO 4 (Latest version)
Game version: 1.0 US (14,383,616 bytes) Just appear a CMD and the game closes on its own.

**Comment by gennariarmando** [comment]
I think you're missing the bass.dll file.

**Comment by Ethmods** [comment]
Likewise, he does not want to open the game and I already tried with anyway and nothing.  Like it's compatibility issues

**Comment by R3SiZT3D** [comment]
Negative, the version .935 removed the cmd but the game does not start, if I remove the .asi the game starts

**Comment by R3SiZT3D** [comment]
When is the next release?

**Comment by alexjhr** [comment]
don't start i get this error
![image](https://user-images.githubusercontent.com/96698651/149683490-fe665262-42bb-4d70-9b7f-fcff99bfe6ff.png)

**Comment by lazytspo** [comment]
it doesn't run for me too :(

**Comment by lazytspo** [comment]
Only, if i do not rely on V HUD next release.

**Comment by lazytspo** [comment]
WAIT! i found the solution! it requires latest version of GInput an Widescreen Fix installed.
