### ISSUE TITLE
List of offers

### ISSUE THREAD

**Issue by EvgeneBooth** [gennariarmando/v-hud#61]
1) Add Russian language
2) Modify into a real third-party system
3) It is not convenient to put labels using the keyboard (The speed of movement is small, I would like to adjust the speed)
4) Add character regeneration like GTA 5
If there are opportunities:
1) Make a more realistic character leveling system (like in GTA 5, so it's not so easy)
2) Add the ability to carry multiple weapons of the same type. For example tec 9 and mini uzi

**Comment by gennariarmando** [comment]
I'm sorry but this is an user interface modifications. 
For new game mechanics, look somewhere else. Thank you.
