### ISSUE TITLE
Weapon wheel assault rifle behavior

### ISSUE THREAD

**Issue by LiaLaylan** [gennariarmando/v-hud#62]
When I open the weapon wheel and try to select an assault rifle, I cannot enter it immediately,
I recorded it because I thought it would be difficult to convey it with just words,

https://youtu.be/WpIL9RSBVaw

Version VHud v0.942
I'm not good at English so I use Google Translate,

**Comment by EvgeneBooth** [comment]
Too ;D

**Comment by gennariarmando** [comment]
Can't replicate this

**Comment by LiaLaylan** [comment]
Installed
-GInput.asi (ControlsSet = 2)
-GTASA.WidescreenFix.asi
-SilentPatchSA.asi
-skygfx.asi
-Ultimate ASI Loader v4.67
-CLEO 4.4.0 (initially included .cleo only)
-modloader 0.3.7 (I haven't installed anything)

Controller used (Xbox One) 

When selecting a weapon other than an assault rifle, you can select it directly as it is, but you can not select it directly unless you enter a stick from another weapon only in the assault rifle frame. 

In order to confirm that there is no abnormality in the controller, the overlay display of the controller is included in the video.
It's not too serious a problem, but I've reported it because you can select it by turning the stick just because you can't select the assault rifle directly. 

(I'm using an interpreter, so I'm really sorry if it's difficult to understand. )

**Comment by gennariarmando** [comment]
That's just normal behaviour and I can't improve it from what I can see.
