### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by EvgeneBooth** [gennariarmando/v-hud#63]
The problem is that the game crashes if other weapon settings are used (in my case, the crash immediately after the start of the 1st cutscene). After returning the original data folder to the game folder, everything works fine

**Comment by EvgeneBooth** [comment]
By the way, when I read about the fact that modloader does not work, then most likely the problem is in the Ultimate Asi Loader. I tried to play with Silent Asi Loader and modloader worked. But there may most likely be compatibility issues.

**Comment by niresh1234** [comment]
Hi, @EvgeneBooth 
You must download this ultimate ASI Loader file
https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/Win32-latest/vorbisFile.zip

and paste VorbisFile.dll to GTA San Andreas Directly (Replace)

**Comment by gennariarmando** [comment]
What does "other weapon settings" means?

**Comment by EvgeneBooth** [comment]
Можно скачать с интернета файл weapon.dat(он находится в папке data) и в нём хранятся характеристики оружия. Дальность стрельбы или урон можно увеличить и наоборот - уменьшить. И из-за его изменения происходил вылет.
P.S. ошибка пропала и извиняюсь за перевод. Он возможно не грамотный
You can download the weapon.dat file from the Internet (it is located in the data folder) and it stores the characteristics of the weapon. The firing range or damage can be increased and vice versa - reduced. And because of his change, there was a departure.
P.S. the error disappeared and I apologize for the translation. He may not be literate
