### ISSUE TITLE
Compatibility with FullNitrousControl 

### ISSUE THREAD

**Issue by LiaLaylan** [gennariarmando/v-hud#66]
Compatibility with Full Nitrous Control, which was one of the features of GTA IV Hud, one of my favorite mods.
I loved the capacity gauge next to the radar, so I wanted it to be adapted to the V-Hud.

**Comment by gennariarmando** [comment]
Added on the hud so it uses the special ability bar in order to keep the aesthetics.

Screenshot:
![image](https://user-images.githubusercontent.com/24763112/153305220-7c3a64b3-a0c9-456a-bea0-2abaa1d73eb8.png)
