### ISSUE TITLE
Buying real estate

### ISSUE THREAD

**Issue by EvgeneBooth** [gennariarmando/v-hud#67]
When buying a property, there are no inscriptions like "You bought this property".

**Comment by gennariarmando** [comment]
![Grand Theft Auto  San Andreas Screenshot 2022 02 10 - 16 26 25 20](https://user-images.githubusercontent.com/24763112/153439581-45ebe474-6ce8-436c-bbfd-6d9fe7d5c589.png)
Look the right bottom corner.
