### ISSUE TITLE
Controls are broken!

### ISSUE THREAD

**Issue by BlackLover13** [gennariarmando/v-hud#68]
The mapping of the controls is too broken, for example: When I want to aim and shoot these RMB and LMB are pressed at the same time making it impossible to aim without shooting simultaneously. Another example is flight control as it is impossible to tilt air vehicles back and forth (if I change the controls in the menu it causes me to not be able to move ground vehicles normally). There is also the error that when trying to put a cheat that contains the letter "P" it will be impossible since this key opens the menu.

**To Reproduce**
1. Try to aim and type cheat with either the custom or default controls

**Expected behavior**
I think something must be wrong with the "controls.xml" file

**Screenshots**
non applicable

**Additional context**
The only mods I have are the Essentials from the Mixmods page

**Comment by gennariarmando** [comment]
Some aircraft controls are missing, this is known.
There are no aiming issue, try without other mods.
Letter 'P' to open the menu has been disabled in recent commits and will be in the next release.

**Comment by BlackLover13** [comment]
> 

Thanks for answering my questions, I don't have another mod installed apart from ESSENTIALS but I'll see how to solve the problem with aiming and shooting anyway 
😊
