### ISSUE TITLE
Text looks blurry

### ISSUE THREAD

**Issue by NI7RO25** [gennariarmando/v-hud#69]
this never happened before, i even try with the old version and still got the same issue.
![Screenshot (29)](https://user-images.githubusercontent.com/98686901/153524762-7e51c413-f6d3-4033-b685-8030ace9deaf.png)
![Screenshot (30)](https://user-images.githubusercontent.com/98686901/153524808-89245ea3-37c3-456c-8fbd-ff51260fbf8c.png)

it could be my windows settings but i don't know which setting that caused this. maybe you or someone can help

**Comment by gennariarmando** [comment]
Try opening the fonts.xml file and increase the "Quality" value.

**Comment by NI7RO25** [comment]
> Try opening the fonts.xml file and increase the "Quality" value.

still the same. i guess it's my windows setting then...
