### ISSUE TITLE
I can't move the camera

### ISSUE THREAD

**Issue by MartiMGA** [gennariarmando/v-hud#70]
**Describe the bug**
Camera doesn't work while playing with a mouse, not even aiming, but it works when playing with a controller

**To Reproduce**
1. Use a mouse while playing

**Additional context**
I tried it on a GTA with and without mods, and it doesn't work on any of them

**Comment by gennariarmando** [comment]
I can't fix issues that are present only on your machine, try deleting userfiles or change mouse sensitivity settings.
