### ISSUE TITLE
VHud will not run

### ISSUE THREAD

**Issue by lazytspo** [gennariarmando/v-hud#72]
**Describe the bug**
Everytime i installed VHud, the ASI of VHud will not work

**To Reproduce**
1. Install VHud
2. You will notice that VHud will not work

**Expected behavior**
VHud runs successfully

**Comment by EvgeneBooth** [comment]
Write what mods you use and what kind of Asi Loader you have

**Comment by lazytspo** [comment]
> Write what mods you use and what kind of Asi Loader you have

i am using Silent's ASI Loader
and oh! i used VHud 0.942

**Comment by BlackLover13** [comment]
> > Write what mods you use and what kind of Asi Loader you have
> 
> i am using Silent's ASI Loader and oh! i used VHud 0.942

Try the ESSENTIALS mod and CrashInfo (both from the Mixmods page) I hope they can help you and if not, I'm sorry.
