### ISSUE TITLE
Shooting from a car + a wheel of weapons in transport

### ISSUE THREAD

**Issue by EvgeneBooth** [gennariarmando/v-hud#73]
Please add a weapon wheel in transport + add the ability to shoot from a car
![изображение](https://user-images.githubusercontent.com/98256114/153713560-86c8616b-59c7-417d-9a1d-71a46c2f5ee1.png)
Sorry for the small size of the screenshot

**Comment by gennariarmando** [comment]
That’s a UI modification. No game mechanics will be implemented.
