### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by EvgeneBooth** [gennariarmando/v-hud#74]
2 bugs were noticed during the game:
1) For some reason, the helicopter's field of view does not work.
2) When I pause the game and switch to another application, for some reason I hear the game and can control it. I go in, and I'm not on pause anymore
A flaw:
The hydra does not show auto-aiming and sight at all. The same with an RPG with auto-aiming
![изображение](https://user-images.githubusercontent.com/98256114/153927502-ae3de031-afec-4f12-a211-ccd4048f663c.png)
3 bug: gang territories are not shown on the map in the game menu

**Comment by EvgeneBooth** [comment]
Are you ignoring me?

**Comment by TemporaryPSP** [comment]
While we're at it, add rocket launcher's crosshair to Hunter/Hydra's first person camera.

**Comment by EvgeneBooth** [comment]
By the way, when will the new version be released?

**Comment by EvgeneBooth** [comment]
Where are the updates...
