### ISSUE TITLE
Can't select camera after buying weapon

### ISSUE THREAD

**Issue by Crono23** [gennariarmando/v-hud#77]
**Describe the bug**
I can't seem to select the camera from the weapon wheel after buying a weapon.

**To Reproduce**
1. Get a camera
2. Buy a weapon
3. Try switching to the camera

**Expected behavior**
Camera should be able to be selected.

**Screenshots**
[Before buying weapon](https://www.dropbox.com/s/stoh73yiql6nh5t/Before.png?dl=0)
[After buying weapon](https://www.dropbox.com/s/m5nuamsjto6exw7/After.png?dl=0)

**Additional context**
Found the bug while trying to finish the "Badlands" mission.

**Comment by gennariarmando** [comment]
So you are actually pressing TAB + mouse wheel on the fist slot and camera doesn't pop in?

**Comment by Crono23** [comment]
Ahh I didn't know about using TAB, I was using mouse wheel only. Just tried it and it works lol, thanks!
