### ISSUE TITLE
Motion blur/trails

### ISSUE THREAD

**Issue by TemporaryPSP** [gennariarmando/v-hud#78]
Motion blur/trails when speeding up or using thermal goggles is bugged when using fullscreen. Yes, borderless windowed support was added to remedy this, but not everyone likes to play that way.

How to reproduce:
1. Launch the game in fullscreen mode with low visual quality setting. If you have it higher, change it to low and restart the game
2. Speed up/Use nitro/Equip thermal goggles

Bumping the setting to medium or above then switching back to low fixes this, but it usually crashes.

**Comment by gennariarmando** [comment]
Latest version fixes this. Do you have it yet?

**Comment by TemporaryPSP** [comment]
Yeah, I tested the update before posting this. It's still there.

**Comment by gennariarmando** [comment]
Should be fixed now, can you please test the attached asi file?
[vhud-4725657.zip](https://github.com/gennariarmando/v-hud/files/8261439/vhud-4725657.zip)

**Comment by TemporaryPSP** [comment]
The blur is fixed. Only did a short test though.

**Comment by gennariarmando** [comment]
Close enough, it was actually already fixed but something happened with the latest code changes.
