### ISSUE TITLE
Problam are stil there (using v0.943) - From issue #45

### ISSUE THREAD

**Issue by ghost** [gennariarmando/v-hud#79]
https://github.com/gennariarmando/v-hud/issues/45
Screen bug at High-Speed Vehicle in (Very Low) Graphics Setting...
https://github.com/gennariarmando/v-hud/issues/45

![Screenshot (231)](https://user-images.githubusercontent.com/98110551/156183419-b5c392e7-0af0-4479-9c6d-6cc991e9790a.png)
![Screenshot (232)](https://user-images.githubusercontent.com/98110551/156184525-16945060-5cf9-4821-9a4f-b27e3215dd61.png)
![Screenshot (233)](https://user-images.githubusercontent.com/98110551/156185199-0a761bb2-01e5-4b7c-bba6-c354862dfd7c.png)

**Comment by gennariarmando** [comment]
Duplicate, won’t be fixed.

**Comment by ghost** [comment]
What is duplicate?
Only get this problem when Anti Aliasing Off

If I force *2x* anti Aliasing in _ufiles_ not get the issue (because I and everyone not have GPU to turn on anti Aliasing)
