### ISSUE TITLE
Death effect & camera position 

### ISSUE THREAD

**Issue by Crowdigger** [gennariarmando/v-hud#80]
Add gray screen effect and sound when killing someone 
Thinking about adding GTA 5 camera positions? (When aiming, driving). And thanks for adding modloader menu support.

**Comment by EvgeneBooth** [comment]
https://www.gtainside.com/en/sanandreas/mods/135055-gta-v-full-camera-style-for-gta-sa/ - GTA V Camera Style

**Comment by Crowdigger** [comment]
@EvgeneBooth I've seen this mod, it's not good.

It has many bugs, like when passing close to a pole, the camera bugs).

I believe _AG would do a much better.

**Comment by gennariarmando** [comment]
Won’t happen.
