### ISSUE TITLE
[see video] screen bug at high speed vehicle 

### ISSUE THREAD

**Issue by ghost** [gennariarmando/v-hud#84]
it same time i change       windowed > then back to fullscreen > problem solve

[see full video](https://youtu.be/x604yjcraAE)
https://youtu.be/x604yjcraAE

**Comment by gennariarmando** [comment]
Stop opening issues

**Comment by ghost** [comment]
@gennariarmando 
But, you must try atlist one time
Visual Quality = Low

At visual Quality = medium, high, ............ Not get this issue

Because everyone not have good pc as well as gpu

**Comment by ghost** [comment]
> @gennariarmando But, you must try atlist one time Visual Quality = Low
> 
> At visual Quality = medium, high, ............ Not get this issue
> 
> Because everyone not have good pc as well as gpu

Hi @gennariarmando please test this atleast 2 times
