### ISSUE TITLE
Fastman92 Limit Adjuster - Crash Window Problem

### ISSUE THREAD

**Issue by ghost** [gennariarmando/v-hud#86]
Hi, with Fastman92 Limit Adjuster; The crash window are not showing in front but playing crash window music.. This problem actually fix by [Windowed Mod](https://github.com/ThirteenAG/III.VC.SA.WindowedMode) by @ThirteenAG

But this Hud are not compatible with [Windowed Mod](https://github.com/ThirteenAG/III.VC.SA.WindowedMode), because it's has own Windowed Mod... Can you fix this problem? Same as @ThirteenAG Windowed Mod

See [Attention from Mixmods](https://www.mixmods.com.br/2022/01/fastman92-limit-adjuster/) 
![Screenshot_20220312_190651](https://user-images.githubusercontent.com/98110551/158020137-4a7f3aa6-30ff-44bd-8fd9-004f3226d8c9.jpg)

**Comment by gennariarmando** [comment]
No, use alt+tab to cycle through your windows.
