### ISSUE TITLE
Is there an option to activate the icons added by other mods? - Problems with the spanish translation

### ISSUE THREAD

**Issue by TheAngelOfDeath** [gennariarmando/v-hud#87]
problem 1
I tried to install the mod "More Radar Icons v2.0 - Junior_Djjr" but when I install the v-hud the icons stop appearing Is there a solution or option that I'm missing? 

problem 2
I also made the translation of the mod to the Spanish language (my native language) using exactly the same texts that the GTA V menu uses in Spanish, so the menu texts already change to Spanish when changing the language of the game, but... the subtitles of the game in Spanish are broken due to the mod, I opened the spanish.gxt file in the game's text folder and saw that Rockstar wrote everything in Spanish but avoiding putting important symbols for the language, playing without the mod the symbols appear normally but with this mod the subtitles are loaded exactly the same as how they are written in the spanish.gxt of the game

**Comment by gennariarmando** [comment]
https://github.com/gennariarmando/v-hud#incompatibility

Adding support to more languages it's not possible yet.
